<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-KGDMBK1V" failures="0" tests="6" name="com.practicepararmeter.DependancyDemo" time="0.019" errors="1" timestamp="19 Oct 2021 10:38:33 GMT" skipped="1">
  <testcase classname="com.practicepararmeter.DependancyDemo" name="s14" time="0.002"/>
  <testcase classname="com.practicepararmeter.DependancyDemo" name="s15" time="0.001"/>
  <testcase classname="com.practicepararmeter.DependancyDemo" name="s11" time="0.002">
    <error type="java.lang.ArithmeticException">
      <![CDATA[java.lang.ArithmeticException
at com.practicepararmeter.DependancyDemo.s11(DependancyDemo.java:10)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- s11 -->
  <testcase classname="com.practicepararmeter.DependancyDemo" name="s16" time="0.002"/>
  <testcase classname="com.practicepararmeter.DependancyDemo" name="s12" time="0.012"/>
  <testcase classname="com.practicepararmeter.DependancyDemo" name="s13" time="0.000">
    <skipped/>
  </testcase> <!-- s13 -->
</testsuite> <!-- com.practicepararmeter.DependancyDemo -->
